### ISSUE TITLE
Cannot read property 'add' of undefined 

### ISSUE THREAD

**Issue by 1StepEngineer** [w3c-king/parcel-vue#2]
按照步骤做完后，` npm run dev `显示`Cannot read property 'add' of undefined `   不知道什么问题

**Comment by 1StepEngineer** [comment]
今天又试了下 还是不行 求解是什么问题

**Comment by KevinLjb** [comment]
能方便截个图吗？还有运行环境简单说一下

**Comment by Haoran8862** [comment]
![image](https://user-images.githubusercontent.com/29394174/36071176-260f47d6-0f45-11e8-8ec5-f307f4b9f505.png)

我遇到一样的问题

**Comment by w3c-king** [comment]
经过测试，初步确定是windows系统下的bug，目前正在定位问题所在，同时也可以通过下方二维码添加微信交流，待修复完毕第一时间通知：
![image](https://user-images.githubusercontent.com/24582461/36074542-23f5d1a4-0f7c-11e8-954a-fa2bc1dc89e4.png)

**Comment by KevinLjb** [comment]
在最新版本1.3.2中此问题已修复,请更新

**Comment by KevinLjb** [comment]
npm install parcel-vue -g

**Comment by jiawanlong** [comment]
在线等

**Comment by jiawanlong** [comment]
Cannot read property 'add' of undefined

**Comment by KevinLjb** [comment]
最新版本中已修复，麻烦重新安装一次parcel-vue工具，即可解决

**Comment by jiawanlong** [comment]
可以了，**多谢**
